[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Markus Sommer <markus@splork.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
